// THIS SITE'S OWN FILE. Not generated by gen-docs-lib.js, and named in it under
// OWN. The portal has nothing to generate it from: it has no build step at all,
// which is the rule 16e makes this site the stated exception to.
//
// **What `scripts/build.js` leaves behind for the functions to read.** The build
// runs before the functions are packaged, so anything it writes into
// `api/_generated/` travels with them through the `includeFiles` entry in
// vercel.json. Nothing else writes there and nothing there is committed.
//
//   updated.json          every page's last commit date, per 16e
//   search-poster.json    the search index for exactly that tier
//   search-admin.json     "
//   search-developer.json "
//
// **The two files fail differently, on purpose.**
//
//   A missing date is a gap, and phase 12's rule is that a gap is data and
//   nothing is allowed to fill it in. A page git could not date -- one that has
//   never been committed, or one older than the clone depth -- carries no date,
//   and the page draws none rather than today's.
//
//   A missing search index is not a gap, it is a wrong answer. Serving an empty
//   list would tell a reader their words appear nowhere in the staff guides,
//   which is a sentence this site would be making up. So it throws, and the
//   message names the command that was not run.
//
// Both come out of the same build, so the loud one is what says the build did not
// happen. The quiet one is only ever quiet about a page.

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import { projectRoot } from './pages.js';
import { ACCESS_VALUES, tierRank } from './tiers.js';

const GENERATED_DIR = 'api/_generated';

/** The one sentence anybody who has not run the build needs to read. */
const HOW = 'Run: node scripts/build.js  (it is the docs project\'s Build Command)';

const cache = new Map();

function read(name, { required }) {
  if (cache.has(name)) return cache.get(name);

  const file = join(projectRoot(), GENERATED_DIR, name);
  let value = null;

  if (existsSync(file)) {
    value = JSON.parse(readFileSync(file, 'utf8'));
  } else if (required) {
    throw new Error(`${GENERATED_DIR}/${name} is missing. ${HOW}`);
  }

  cache.set(name, value);
  return value;
}

/**
 * When a page was last changed, as an ISO date, or null.
 *
 * @param {string} path a page path, as pages.js builds them
 * @returns {string|null}
 */
export function updatedFor(path) {
  const dates = read('updated.json', { required: false });
  return dates?.[path] ?? null;
}

/**
 * The gated search index for one reader, and never a line of it for anyone else.
 *
 * One file per tier and never a merged one, per 16e, so a reader is handed the
 * concatenation of the tiers at or below their own. **The public entries are not
 * in any of them**: the browser already has that index as a static file, and the
 * one thing this endpoint must not do is become the place both halves meet.
 *
 * @param {string} readerAccess from readerTier
 * @returns {Array<object>} empty for a signed out reader, without reading a file
 */
export function gatedIndexFor(readerAccess) {
  const rank = tierRank(readerAccess);
  if (rank === null) return [];

  const out = [];
  for (const tier of ACCESS_VALUES) {
    if (tier === 'public' || tierRank(tier) > rank) continue;
    out.push(...(read(`search-${tier}.json`, { required: true }) ?? []));
  }

  return out;
}
