// THIS SITE'S OWN FILE. Not generated by gen-docs-lib.js, and named in it under
// OWN. The portal has nothing to generate it from: it has no build step at all,
// which is the rule 16e makes this site the stated exception to.
//
// **What `scripts/build.js` leaves behind for the functions to read.** The build
// runs before the functions are packaged, so anything it writes into
// `api/_generated/` travels with them through the `includeFiles` entry in
// vercel.json. Nothing else writes there and nothing there is committed.
//
//   updated.json          every page's last commit date, per 16e
//   search-poster.json    the search index for exactly that tier
//   search-admin.json     "
//   search-developer.json "
//   search-poster.zh.json the same, per language, since part 9. A page with no
//   ...                   translation is in them in English, so a reader
//                         searching a word that is on the screen finds it.
//
// **The two files fail differently, on purpose.**
//
//   A missing date is a gap, and phase 12's rule is that a gap is data and
//   nothing is allowed to fill it in. A page git could not date -- one that has
//   never been committed, or one older than the clone depth -- carries no date,
//   and the page draws none rather than today's.
//
//   A missing search index is not a gap, it is a wrong answer. Serving an empty
//   list would tell a reader their words appear nowhere in the staff guides,
//   which is a sentence this site would be making up. So it throws, and the
//   message names the command that was not run.
//
// Both come out of the same build, so the loud one is what says the build did not
// happen. The quiet one is only ever quiet about a page.

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import { projectRoot } from './pages.js';
import { ACCESS_VALUES, tierRank } from './tiers.js';

const GENERATED_DIR = 'api/_generated';

/** The language the files themselves are written in, per 3a. */
const BASE_LOCALE = 'en';

/** The one sentence anybody who has not run the build needs to read. */
const HOW = 'Run: node scripts/build.js  (it is the docs project\'s Build Command)';

const cache = new Map();

function read(name, { required }) {
  if (cache.has(name)) return cache.get(name);

  const file = join(projectRoot(), GENERATED_DIR, name);
  let value = null;

  if (existsSync(file)) {
    value = JSON.parse(readFileSync(file, 'utf8'));
  } else if (required) {
    throw new Error(`${GENERATED_DIR}/${name} is missing. ${HOW}`);
  }

  cache.set(name, value);
  return value;
}

/**
 * When a page was last changed, as an ISO date, or null.
 *
 * **A translated page has two dates and the later one is the answer.** Phase 14
 * part 9: the English page and its translation are two files with two histories,
 * so a guide written in March whose 华文 was rewritten in September changed in
 * September for the reader looking at the Chinese. Anything else tells them the
 * page in front of them is older than it is.
 *
 * The same rule is in `gftvjobs_docs_public`, as a `greatest()` over the two
 * columns, so the site and the Telegram bot cannot answer this differently for
 * the same page. That is the whole reason this takes a locale at all.
 *
 * The dates are `YYYY-MM-DD`, which compares correctly as text, and either half
 * can be absent: `updated.json` carries only what git could date, per the rule
 * `scripts/build.js` states twice.
 *
 * @param {string} path a page path, as pages.js builds them
 * @param {string|null} [locale] the language the page is being served in
 * @returns {string|null}
 */
export function updatedFor(path, locale = null) {
  const dates = read('updated.json', { required: false });
  const base = dates?.[path] ?? null;

  if (!locale || locale === BASE_LOCALE) return base;

  const translated = dates?.[`${locale}:${path}`] ?? null;
  if (!translated) return base;
  if (!base) return translated;

  return translated > base ? translated : base;
}

/**
 * The gated search index for one reader, and never a line of it for anyone else.
 *
 * One file per tier and never a merged one, per 16e, so a reader is handed the
 * concatenation of the tiers at or below their own. **The public entries are not
 * in any of them**: the browser already has that index as a static file, and the
 * one thing this endpoint must not do is become the place both halves meet.
 *
 * @param {string} readerAccess from readerTier
 * @returns {Array<object>} empty for a signed out reader, without reading a file
 */
export function gatedIndexFor(readerAccess, locale = null) {
  const rank = tierRank(readerAccess);
  if (rank === null) return [];

  const out = [];
  for (const tier of ACCESS_VALUES) {
    if (tier === 'public' || tierRank(tier) > rank) continue;

    // **The language's index is optional and the English one is not.** The
    // build writes one file per tier per language, so a missing localised file
    // means either a language that arrived without a rebuild or a locale
    // nobody translates into. Either way the honest answer is the English
    // index, which is also what those pages are served as. A missing English
    // index is still the loud failure the header describes: it means the build
    // did not run, and an empty list would tell a reader their words appear
    // nowhere in the staff guides.
    const localised = locale ? read(`search-${tier}.${locale}.json`, { required: false }) : null;
    out.push(...(localised ?? read(`search-${tier}.json`, { required: true }) ?? []));
  }

  return out;
}
