// Turn tests/*.mjs into something the developer guide can hand a reader.
//
//   node docs-site/scripts/embed-tests.mjs            print it
//   node docs-site/scripts/embed-tests.mjs --out FILE write it
//   node docs-site/scripts/embed-tests.mjs --check FILE  fail if out of date
//
// Run it whenever a script in tests/ changes. It prints by default and writes
// nothing unless it is told where: the docs site has no content pipeline until
// phase 13, and a generator that invents a directory to put its output in is a
// decision made in the wrong place.
//
// **Why the file is embedded instead of linked.** A plain link would have to
// point at a path that serves the raw file, and that path is then the thing
// people share, bookmark, and script against: a second public surface for a
// file whose only supported entry point is the guide page that explains what it
// writes to the live database. Embedding it and building a blob: URL in the
// browser means the download works exactly as a reader expects, and the address
// behind it belongs to that one tab and dies with it.
//
// **What that is not.** A blob: URL hides where the file came from, not what is
// in it. The text is in the page, so anybody who opens the network tab or view
// source has it. Nothing here is a secret and nothing here should be: the
// scripts carry no credentials, they take them from the environment, and the
// pages that carry them are behind the staff login anyway. If a script ever
// needs to hold something that must not be read, it does not go in tests/.

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const TESTS = join(ROOT, 'tests');

/** --out FILE or --check FILE, whichever was given. No default. */
function flagValue(flag) {
  const index = process.argv.indexOf(flag);
  if (index === -1) return null;
  const value = process.argv[index + 1];
  return value && !value.startsWith('--') ? resolve(value) : null;
}

const CHECK = process.argv.includes('--check');
const OUT = flagValue('--out') ?? flagValue('--check');

/**
 * The first paragraph of the file's opening comment block, as its description.
 *
 * Every script in tests/ starts by saying what it does, so there is no second
 * place to keep a summary that could fall out of step with the file it
 * describes. A script that starts with something else gets no description
 * and not a wrong one.
 */
function describe(source) {
  const lines = source.split('\n');
  const comment = [];

  for (const line of lines) {
    if (!line.startsWith('//')) break;
    comment.push(line.replace(/^\/\/ ?/, ''));
  }

  const paragraph = [];
  for (const line of comment) {
    if (line.trim() === '' && paragraph.length > 0) break;
    if (line.trim() !== '') paragraph.push(line.trim());
  }

  return paragraph.join(' ') || null;
}

/**
 * The usage lines, which are the indented commands under the description.
 *
 * Shown beside the download, because the thing a reader needs at the same
 * moment as the file is the line that runs it.
 */
function usage(source) {
  const lines = source.split('\n');
  const found = [];

  for (const line of lines) {
    if (!line.startsWith('//')) break;
    const text = line.replace(/^\/\//, '');
    // Indented, and a command, not prose. Every script here writes its
    // example invocations indented under the description, and the indent alone
    // also catches the wrapped lines of an explanation, which are not commands.
    if (/^ {3,}\S/.test(text) && /\b(node|npx|npm)\b/.test(text)) found.push(text.trim());
  }

  return found;
}

const files = (await readdir(TESTS))
  .filter((name) => name.endsWith('.mjs'))
  .sort();

const scripts = [];

for (const name of files) {
  const source = await readFile(join(TESTS, name), 'utf8');

  scripts.push({
    name,
    description: describe(source),
    usage: usage(source),
    bytes: Buffer.byteLength(source, 'utf8'),
    lines: source.split('\n').length,
    // So a reader can tell two versions apart, and so --check has something to
    // compare that does not change when only this generator changes.
    sha256: createHash('sha256').update(source).digest('hex'),
    // base64 over the raw string, so the JSON is not something a
    // markdown pipeline or a template engine will try to interpret on the way
    // through. The client decodes it before making the blob.
    content: Buffer.from(source, 'utf8').toString('base64'),
  });
}

const payload = {
  $comment:
    'Generated by docs-site/scripts/embed-tests.mjs from tests/*.mjs. Do not edit by hand; run the generator.',
  generated: new Date().toISOString().slice(0, 10),
  count: scripts.length,
  scripts,
};

const serialised = `${JSON.stringify(payload, null, 2)}\n`;

if (CHECK) {
  if (!OUT) {
    console.error('--check needs the file to compare against: --check path/to/test-scripts.json');
    process.exit(1);
  }

  let existing = null;
  try {
    existing = await readFile(OUT, 'utf8');
  } catch {
    console.error(`${OUT} does not exist. Run the generator with --out.`);
    process.exit(1);
  }

  // The date changes on every run and says nothing about whether the content
  // is current, so the comparison is on the scripts alone.
  const before = JSON.stringify(JSON.parse(existing).scripts);
  const after = JSON.stringify(payload.scripts);

  if (before !== after) {
    console.error('test-scripts.json is out of date. Run: node docs-site/scripts/embed-tests.mjs');
    process.exit(1);
  }

  console.log(`${OUT} is current: ${scripts.length} scripts.`);
  process.exit(0);
}

if (OUT) {
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, serialised, 'utf8');
  console.log(`Wrote ${OUT}`);
  for (const script of scripts) {
    console.log(
      `  ${script.name.padEnd(24)} ${String(script.lines).padStart(5)} lines  ${script.sha256.slice(0, 12)}`
    );
  }
} else {
  // Nowhere to put it, so it goes to stdout and the caller decides. Piping it
  // is also how a content pipeline would consume it.
  process.stdout.write(serialised);
}
